"""
Fallback bot messages for when the LLM service is unavailable.
Used only as a safety net — all normal responses are generated by LLM.
"""

MESSAGES = {
    "ru": {
        "error": "Произошла ошибка. Попробуйте снова или обратитесь по номеру 1433.",
        "timeout": "Извините, мы не смогли собрать всю информацию. Ваше обращение передано оператору.",
    },
    "kz": {
        "error": "Қате орын алды. Қайта көріңіз немесе 1433 нөміріне хабарласыңыз.",
        "timeout": "Кешіріңіз, барлық ақпаратты жинай алмадық. Өтінішіңіз операторға жіберілді.",
    },
    "en": {
        "error": "An error occurred. Please try again or call 1433.",
        "timeout": "Sorry, we could not collect all the information. Your request has been forwarded to an operator.",
    },
}


def get_message(lang: str, key: str) -> str:
    """Get a localized fallback message by key. Falls back to Russian."""
    return MESSAGES.get(lang, MESSAGES["ru"]).get(key, MESSAGES["ru"].get(key, ""))
